template-file-path: template.yaml
parameters:
  VpcCidr: 10.0.0.0/16
  SubnetCidrPublic1: 10.0.1.0/24
  SubnetCidrPublic2: 10.0.2.0/24
  SubnetCidrPrivate1: 10.0.3.0/24
  SubnetCidrPrivate2: 10.0.4.0/24
  ProjectTag: auto-scaling-lab
  InstanceType: t2.micro
  CPUPolicyTargetValue: 50
  LatestAmazonLinuxAMI: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
tags: {}
